### ISSUE TITLE
/glist is not overriden

### ISSUE THREAD

**Issue by andreasdc** [ProxioDev/RedisBungee#61]
When you use /glist it only shows players from current proxy, it uses default bungee's command.

**Comment by linsaftw** [comment]
FlameCord has it's own module system. You can't override it.

**Comment by ham1255** [comment]
RedisBungee config:
```yml
# Register redis bungee legacy commands
# if this disabled override-bungee-commands will be ignored
register-legacy-commands: false

# Whether or not RedisBungee should install its version of regular BungeeCord commands.
# Often, the RedisBungee commands are desired, but in some cases someone may wish to
# override the commands using another plugin.
#
# If you are just denying access to the commands, RedisBungee uses the default BungeeCord
# permissions - just deny them and access will be denied.
#
# Please note that with build 787+, most commands overridden by RedisBungee were moved to
# modules, and these must be disabled or overridden yourself.
override-bungee-commands: false
```
